### ISSUE TITLE
Freeze .md files

### ISSUE THREAD

**Issue by riju-dc** [dat-labs/dat-main#12]
- README.md
- CONTRIBUTING.md
  - only for verified-*
- CODE_OF_CONDUCT.md
  - Only for dat-main repo
- DEV_GUIDE.md
  - only for verified-*

**Comment by riju-dc** [comment]
@suryaanshrai Please take this up.

**Comment by suryaanshrai** [comment]
Done. Please review relevant repositories for PRs. Attaching them here for easier reference.

https://github.com/dat-labs/verified-sources/pull/26/files
https://github.com/dat-labs/verified-generators/pull/7/files
https://github.com/dat-labs/verified-destinations/pull/19/files

**Comment by riju-dc** [comment]
Thanks @suryaanshrai
